### ISSUE TITLE
[Feature] Use an existing markdown library to parse markdown

### ISSUE THREAD

**Issue by lmpham1** [lmpham1/cool_ssg_generator#28]
## Description

Currently, the markdown codes are parsed internally inside `html_generator_utils.py`. It is better to use a popularly used external markdown library to tackle this feature instead, as they cover most markdown syntax, are more standardized, and are more well tested. 

The library we want to use is [`Python-Markdown`](https://github.com/Python-Markdown/markdown).

## Tasks

- [ ] Add `Python-Markdown` as a dependency (including `environment.yml` and `requirements.txt`)
- [ ] Replace the markdown parsing code in `html_generator_utils.py` to use `Python-Markdown` library instead
- [ ] Test it with `pytest`:
```
pytest .
```
